[package]
name = "my_crate"
version = "0.1.0"
authors = ["upendra singh <uvsingh2336@gamil.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html




[features]
xyz = []
pqr =[]



